
import plotly.graph_objects as go
import pandas as pd
from typing import List, Dict, Any, Tuple

def create_empty_grid(grid_size: Tuple[int, int]) -> go.Figure:
    """Creates an empty plot with a title and configured axes."""
    fig = go.Figure()
    fig.update_layout(
        title="ADRIE Mission Control - Live Simulation",
        xaxis=dict(range=[-1, grid_size[0]], showgrid=False, zeroline=False, visible=False),
        yaxis=dict(range=[-1, grid_size[1]], showgrid=False, zeroline=False, visible=False, scaleanchor="x", scaleratio=1),
        plot_bgcolor='#1E1E1E',
        paper_bgcolor='#1E1E1E',
        font=dict(color='white'),
        showlegend=True,
        legend=dict(x=0, y=1, traceorder="normal", bgcolor="rgba(0,0,0,0.5)")
    )
    return fig

def add_grid_elements(fig: go.Figure, elements: List[Dict[str, Any]], marker_style: Dict, name: str, hover_template: str):
    """Generic function to add elements (victims, agents) to the grid."""
    if not elements:
        return
    df = pd.DataFrame(elements)
    fig.add_trace(go.Scatter(
        x=df['x'], y=df['y'],
        mode='markers+text',
        marker=marker_style,
        name=name,
        text=df.get('id', ''),
        textposition="top center",
        hoverinfo='text',
        hovertext=[hover_template.format(**el) for el in elements]
    ))

def add_hazards(fig: go.Figure, hazards: List[Dict[str, Any]]):
    """Adds hazard zones to the grid as filled shapes."""
    if not hazards:
        return
    for hazard in hazards:
        area = hazard.get('area', [])
        if not area or len(area) != 2:
            continue
        
        x0, y0 = area[0]
        x1, y1 = area[1]
        
        hazard_color = {
            "flood": "rgba(0, 116, 217, 0.4)",
            "fire": "rgba(255, 65, 54, 0.4)",
            "rubble": "rgba(133, 133, 133, 0.4)"
        }.get(hazard.get('type', 'rubble'), "rgba(133, 133, 133, 0.4)")
        
        fig.add_shape(
            type="rect",
            x0=x0, y0=y0, x1=x1, y1=y1,
            line=dict(width=0),
            fillcolor=hazard_color,
            layer="below",
            name=hazard.get('type')
        )

def add_paths(fig: go.Figure, plan: Dict[str, Any]):
    """Adds agent paths to the grid."""
    if not plan or 'plan' not in plan:
        return
        
    colors = ['#FFDD00', '#00FFFF', '#FF00FF', '#00FF00'] # Bright colors for paths
    
    for i, agent_plan in enumerate(plan.get('plan', [])):
        agent_id = agent_plan['agent_id']
        steps = agent_plan.get('steps', [])
        if not steps:
            continue

        path_x = [step['to'][0] for step in steps if step['action'] == 'move']
        path_y = [step['to'][1] for step in steps if step['action'] == 'move']
        
        # Need to find agent start position
        # This is a limitation; we assume it's the first 'move' point's origin for now
        # A better implementation would pass the agent's start pos to this function
        
        fig.add_trace(go.Scatter(
            x=path_x,
            y=path_y,
            mode='lines',
            line=dict(color=colors[i % len(colors)], width=2, dash='dash'),
            name=f'Path {agent_id}'
        ))

def render_simulation_grid(
    grid_size: Tuple[int, int],
    victims: List[Dict[str, Any]],
    agents: List[Dict[str, Any]],
    hazards: List[Dict[str, Any]],
    plan: Dict[str, Any] = None
) -> go.Figure:
    """
    Renders the complete simulation grid with all elements.
    
    Args:
        grid_size: Tuple of (width, height).
        victims: List of victim dictionaries.
        agents: List of agent dictionaries.
        hazards: List of hazard dictionaries.
        plan: The plan generated by Gemini, used to draw paths.

    Returns:
        A Plotly Figure object.
    """
    fig = create_empty_grid(grid_size)

    # Add Hazards first to be in the background
    add_hazards(fig, hazards)

    # Add Victims
    victim_style = dict(color='red', size=15, symbol='x')
    add_grid_elements(fig, victims, victim_style, 'Victims',
                      '<b>Victim {id}</b><br>Risk: {risk}<br>Type: {type}<br>Status: {status}')

    # Add Agents
    agent_style = dict(color='cyan', size=12, symbol='circle')
    add_grid_elements(fig, agents, agent_style, 'Agents',
                      '<b>Agent {id}</b><br>Type: {type}<br>Capacity: {capacity}')
                      
    # Add Paths if a plan is provided
    if plan:
        add_paths(fig, plan)

    return fig

# Example usage for testing
if __name__ == '__main__':
    test_grid_size = (20, 20)
    test_victims = [
        {"id": "v1", "x": 2, "y": 3, "risk": 0.9, "type": "drowning", "status": "unattended"},
        {"id": "v2", "x": 15, "y": 12, "risk": 0.6, "type": "injured", "status": "unattended"},
    ]
    test_agents = [
        {"id": "A1", "x": 0, "y": 0, "type": "MedicalBot", "capacity": 1},
        {"id": "A2", "x": 19, "y": 19, "type": "FireBot", "capacity": 1}
    ]
    test_hazards = [
        {"type": "flood", "area": [[0,0], [5,5]]},
        {"type": "fire", "area": [[12,10], [18,15]]}
    ]
    test_plan = {
      "plan": [
        {
          "agent_id": "A1",
          "steps": [
            {"action": "move", "to": [1, 2]},
            {"action": "move", "to": [2, 3]},
            {"action": "rescue", "victim_id": "v1"}
          ],
          "priority": "High", "eta": 60
        }
      ]
    }

    fig = render_simulation_grid(test_grid_size, test_victims, test_agents, test_hazards, test_plan)
    fig.show()
